# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_author', models.CharField(max_length=70)),
                ('author_profile_pic', models.ImageField(blank=True, null=True, upload_to='uploads/authorprofilepics/')),
                ('author_profile', models.TextField(max_length=250)),
                ('article', models.TextField()),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
