# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_link_fb',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='author_link_ig',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='author_link_li',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='author_link_tw',
            field=models.URLField(blank=True),
        ),
    ]
